src/csvs/urls.py
from django.urls import path
from .views import upload_file_view


app_name = 'csvs'

urlpatterns = [
	path('', upload_file_view, name='upload-view'),


]

src/customers/urls.py
from django.urls import path
from .views import customer_corr_view


app_name = 'customers'

urlpatterns = [
	path('', customer_corr_view, name='main-customers-view'),
]

src/dj_pd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view,login_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_view, name='home'),
    path("login/", login_view, name='login'),
    path("performance/", include('products.urls', namespace='products')),
    path("upload/", include('csvs.urls', namespace='csvs')),
    path("customers/", include('customers.urls', namespace='customers')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

src/products/urls.py
from django.urls import path
from .views import chart_select_view, add_purchase_view, sales_dist_view

app_name = 'products'

urlpatterns = [
	path('', chart_select_view, name='main-product-view'),
	path('add/', add_purchase_view, name='add-purchase-view'),
	path('sales/', sales_dist_view, name='sales-view'),
]

src/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel='stylesheet' type='text/css' href={% static 'style.css'  %}>
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

  
    <title>eCommerce {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}

  <div class='ui container'>
    {% block content %}

    {% endblock content %}
  </div>


  <script type='text/javascript' src={% static 'main.js' %}></script>  
  </body>
    
</html>

src/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Home{% endblock title %}

<hr/>
{% block content %}
	<div class='block-center'>
		<h1>Data Analysis</h1>
		<img src={% static 'main_pic.webp' %} class='ui fluid image'>
	</div>

{% endblock content %}

src/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

<hr/>
{% block content %}
	<div class='block-center'>
		{% if error_message %}
			<div class="ui negative message">
			  	  <i class="close icon"></i>
				  <div class="header">
			    	{{ error_message }}
			  	  </div> 
			</div>
		{% endif %}

		<form action="" method = "POST" class="ui form">
			{% csrf_token %}
			{{ form }}
			<button type='submit' class="ui button positive mtop">Login</button>
	    </form>
	</div>

{% endblock content %}
 

src/templates/navbar.html
{% url 'home' as path_to_home %}
{% url 'login' as path_to_login %}
{% url 'products:main-product-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}
{% url 'customers:main-customers-view' as path_to_customers %}

<div class="ui secondary pointing menu">
	 <a href={{path_to_home}} class="{% if request.path == path_to_home %}active{% endif %} item">
	    Home
	  </a>
		{% if request.user.is_authenticated %}
		  <a href={{path_to_performance}} class="{% if request.path == path_to_performance %}active{% endif %} item">
		    Performance
		  </a>
		  <a href={{path_to_adding_records}} class="{% if request.path == path_to_adding_records %}active{% endif %} item">
		    Add records
		  </a>
		   <a href={{path_to_customers}} class="{% if request.path == path_to_customers %}active{% endif %} item">
		    Customers
		  </a>
		  <a href={{path_to_upload}} class="{% if request.path == path_to_upload %}active{% endif %} item">
		    Upload file
		  </a>
		  <div class="right menu">
		    <a class="ui item">
	      		Logout 
	    	</a>
  		  </div>
  		 {% else %}
  		 	<div class="right menu">
		    <a href={{path_to_login}} class="ui item {% if request.path == path_to_login %}active{% endif %}">Login</a>
  		  </div>
  		 {% endif %}
</div>